### ISSUE TITLE
Cannot run with two latest go versions under Ubuntu x86_64

### ISSUE THREAD

**Issue by gokaykucuk** [hsanjuan/mfs-replace-root#2]
Hey, thank you for the tool!. But I couldn't run it with the last 2 versions of go listed on https://go.dev/dl/, `1.17.4` and `1.16.11`. I'm trying to run the tool under `Linux x86_64 Ubuntu 20.04.3 LTS`. 

The error message I get under 1.16.11 when I run `mfs-replace-root` is -> https://gist.github.com/gokaykucuk/3da816e3975969abe9fdb62e48b16276
The error message I get under 1.16.11 when I run `mfs-replace-root` is -> 
```
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        /root/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x132
```

Which architecture/go version can I run this tool with?

**Comment by hsanjuan** [comment]
Let me make a quick upgrade

**Comment by hsanjuan** [comment]
@gokaykucuk should work now?

**Comment by gokaykucuk** [comment]
> @gokaykucuk should work now?

Yep It works. Thanks a lot!
